pipelines:
  default:
    - step:
        name: Build artifact
        image: node:11
        caches:
          - node
        script:
          - yarn
          - yarn build
        artifacts:
          - ./bundle.js

  branches:
    master:
      - step:
          name: Build Application
          image: node:11
          caches:
            - node
          script:
            - yarn
            - yarn build
          artifacts:
            - ./bundle.js
      - step:
          name: Publish on npm
          image: node:11
          caches:
            - node
          script:
            - yarn 
            - yarn update:npm
            - pipe: atlassian/npm-publish:0.2.0
              variables:
                NPM_TOKEN: $NPM_TOKEN
      - step:
          name: Publish on github
          script:
            - git config --global url."https://$GITHUB_TOKEN:@github.com/".insteadOf "https://github.com/"
            - git remote add public https://github.com/fifthbeat/styled-stenciljs
            - git add . 
            - git commit -m "update"
            - git push public